### ISSUE TITLE
"Normal Map not found"

### ISSUE THREAD

**Issue by wikid24** [jtabox/ffxiv-zones-adjustments#1]
![image](https://user-images.githubusercontent.com/19479648/225477012-cb994f13-336b-42b8-a1d9-b601f71b8d73.png)

When attempting to use "Normal to World Space" or "Normal Strength to Half". I am on blender 3.3.4 LTS (I have to use it due to compatibility with other plugins)

**Comment by wikid24** [comment]
Here is a blender function that does it:

```
import bpy

def change_normal_space(space='WORLD', strength=0.5):
    for mat in bpy.data.materials:
        if mat.node_tree:
            for node in mat.node_tree.nodes:
                if node.type == 'NORMAL_MAP':
                    node.space = space
                    node.inputs['Strength'].default_value = strength

# Call the function to change all normal maps to world space and set strength to 0.5
change_normal_space('WORLD', 0.5)
```

**Comment by jtabox** [comment]
Huh, I think when I first wrote the script I was running a 3.3.X version too, but don't remember encountering any errors then.
In any case, I changed the code according to your suggestion, seems to be running fine with my 3.4.1, hopefully it works with 3.3.X versions too.

Thanks for reporting this and for your code suggestion :)
